name: Build and run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v3
    - name: Test
      run: cargo fmt -- --check && TEST_DB=postgres://postgres:postgres@localhost:5432/postgres cargo check --all-features && cargo test --all-features
    - run: rustup component add clippy
    - uses: actions-rs-plus/clippy-check@43303e5bdba1efbf5961020e5743d530fb1de0c1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features
