[global]
default_locale = "en"

[global.translations.en]
title = "Information"
unknown_error = "Unknown error"
loading = "Loading..."
purpose = "Subject"
attributes = "Verified information"
error = "An error occurred"
refresh = "Refresh"
report_move = "Report move"
request_permit = "Request a permit"
request_passport = "Request a passport"
email = "E-mail address"
login_necessary = "Please login to view user information"
login = "Login"
login_expired = "Your session expired or you do not have sufficient permissions to access this resource."
logout = "Logout"
login_successful = "Login successfull. You can close this window."
logout_successful = "Logout successfull. You can close this window."
insufficient_permission = "You do not have sufficient permissions to access this resource."
no_credentials_found = "There are no authenticated guests (yet)"

[global.translations.nl]
title = "Verder Helpen gegevens"
unknown_error = "Onbekende fout"
loading = "Laden..."
purpose = "Onderwerp"
attributes = "Geverifieerde gegevens"
error = "Er is een fout opgetreden"
refresh = "Herladen"
report_move = "Verhuizing doorgeven"
request_permit = "Vergunning aanvragen"
request_passport = "Paspoort aanvragen"
email = "E-mailadres"
login_necessary = "Om gegevens van gebruikers te kunnen zien moet u eerst inloggen"
login = "Inloggen"
login_expired = "Uw sessie is verlopen of u heeft niet voldoende rechten"
logout = "Uitloggen"
login_successful = "U bent ingelogd. U kan dit venster nu sluiten"
logout_successful = "U bent uitgelogd. U kan dit venster nu sluiten"
insufficient_permission = "Uw account heeft niet voldoende rechten, probeer met een ander account in te loggen"
no_credentials_found = "Er zijn (nog) geen geïdentificeerde gasten"
